import "./globals.css";
import { Suspense } from "react";
import { Metadata } from "next";
import { Inter } from "next/font/google";

import Loading from "./loading";
import QueryProvider from "@/src/providers/query-provider";
import { ToastProvider } from "@/src/providers/toaster-provider";
import { ConfettiProvider } from "@/src/providers/confetti-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <ConfettiProvider />
          <ToastProvider />
          <QueryProvider>{children}</QueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
